
const specialtyData = [
  { id: 1, name: "Bipolar" },
  { id: 2, name: "LGBTQ" },
  { id: 3, name: "Medication/Prescribing" },
  { id: 4, name: "Suicide History/Attempts" },
  { id: 5, name: "General Mental Health (anxiety, depression, stress, grief, life transitions)" },
  { id: 6, name: "Men's issues" },
  { id: 7, name: "Relationship Issues (family, friends, couple, etc)" },
  { id: 8, name: "Trauma & PTSD" },
  { id: 9, name: "Personality disorders" },
  { id: 10, name: "Personal growth" },
  { id: 11, name: "Substance use/abuse" },
  { id: 12, name: "Pediatrics" },
  { id: 13, name: "Women's issues (post-partum, infertility, family planning)" },
  { id: 14, name: "Chronic pain" },
  { id: 15, name: "Weight loss & nutrition" },
  { id: 16, name: "Eating disorders" },
  { id: 17, name: "Diabetic Diet and nutrition" },
  { id: 18, name: "Coaching (leadership, career, academic and wellness)" },
  { id: 19, name: "Life coaching" },
  { id: 20, name: "Obsessive-compulsive disorders" },
  { id: 21, name: "Neuropsychological evaluations & testing (ADHD testing)" },
  { id: 22, name: "Attention and Hyperactivity (ADHD)" },
  { id: 23, name: "Sleep issues" },
  { id: 24, name: "Schizophrenia and psychotic disorders" },
  { id: 25, name: "Learning disorders" },
  { id: 26, name: "Domestic abuse" },
];

const randomSpecialty = () => {
  const random1 = Math.floor(Math.random() * 24);
  const random2 = Math.floor(Math.random() * (24 - random1)) + random1 + 1;

  return [random1, random2];
};
const advocateData = [
  {
    firstName: "John",
    lastName: "Doe",
    city: "New York",
    degree: "MD",
    yearsOfExperience: 10,
    phoneNumber: 5551234567,
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    city: "Los Angeles",
    degree: "PhD",
    yearsOfExperience: 8,
    phoneNumber: 5559876543,
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    city: "Chicago",
    degree: "MSW",
    yearsOfExperience: 5,
    phoneNumber: 5554567890,
  },
  {
    firstName: "Michael",
    lastName: "Brown",
    city: "Houston",
    degree: "MD",
    yearsOfExperience: 12,
    phoneNumber: 5556543210,
  },
  {
    firstName: "Emily",
    lastName: "Davis",
    city: "Phoenix",
    degree: "PhD",
    yearsOfExperience: 7,
    phoneNumber: 5553210987,
  },
  {
    firstName: "Chris",
    lastName: "Martinez",
    city: "Philadelphia",
    degree: "MSW",
    yearsOfExperience: 9,
    phoneNumber: 5557890123,
  },
  {
    firstName: "Jessica",
    lastName: "Taylor",
    city: "San Antonio",
    degree: "MD",
    yearsOfExperience: 11,
    phoneNumber: 5554561234,
  },
  {
    firstName: "David",
    lastName: "Harris",
    city: "San Diego",
    degree: "PhD",
    yearsOfExperience: 6,
    phoneNumber: 5557896543,
  },
  {
    firstName: "Laura",
    lastName: "Clark",
    city: "Dallas",
    degree: "MSW",
    yearsOfExperience: 4,
    phoneNumber: 5550123456,
  },
  {
    firstName: "Daniel",
    lastName: "Lewis",
    city: "San Jose",
    degree: "MD",
    yearsOfExperience: 13,
    phoneNumber: 5553217654,
  },
  {
    firstName: "Sarah",
    lastName: "Lee",
    city: "Austin",
    degree: "PhD",
    yearsOfExperience: 10,
    phoneNumber: 5551238765,
  },
  {
    firstName: "James",
    lastName: "King",
    city: "Jacksonville",
    degree: "MSW",
    yearsOfExperience: 5,
    phoneNumber: 5556540987,
  },
  {
    firstName: "Megan",
    lastName: "Green",
    city: "San Francisco",
    degree: "MD",
    yearsOfExperience: 14,
    phoneNumber: 5559873456,
  },
  {
    firstName: "Joshua",
    lastName: "Walker",
    city: "Columbus",
    degree: "PhD",
    yearsOfExperience: 9,
    phoneNumber: 5556781234,
  },
  {
    firstName: "Amanda",
    lastName: "Hall",
    city: "Fort Worth",
    degree: "MSW",
    yearsOfExperience: 3,
    phoneNumber: 5559872345,
  },
];


export { advocateData, specialtyData, randomSpecialty };
